# Generated by Django 5.1.7 on 2025-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                ("date_retrieved", models.DateTimeField(auto_now=True)),
                ("virus_total_details", models.JSONField(blank=True, default=dict)),
                ("is_malicious", models.BooleanField(default=False)),
            ],
        ),
    ]
